export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const USER_LOGGED = "USER_LOGGED"
export const USER_NO_LOGGED = "USER_NO_LOGGED"
export const SET_AVATAR = "SET_AVATAR"
export const DELETE_AVATAR = "DELETE_AVATAR"
export const SET_POST_PHOTO = "SET_POST_PHOTO"
export const REMOVE_POST_PHOTO = "REMOVE_POST_PHOTO"